baseURL = 'http://homelab.:8080/'
title = 'Chi đoàn Trường Tiểu học Đặng Cương'

theme = 'LoveIt'
defaultContentLanguage = 'vi'

[params]
  defaultTheme = 'auto'
  dateFormat = '02/01/2006'
  [params.list]
    dateFormat = '02/01'
  [params.header]
    [params.header.title]
      name = 'Chi đoàn Trường Tiểu học Đặng Cương'
      pre = '<img width="30px" src="https://upload.wikimedia.org/wikipedia/vi/0/09/Huy_Hi%E1%BB%87u_%C4%90o%C3%A0n.png" />'
      typeIt = true
  [params.home]
    [params.home.profile]
      enable = false
      title = 'Xin chào'
      subtitle = 'Chi đoàn Trường Tiểu học Đặng Cương'
      avatarURL = 'images/avatar.webp'
  [params.author]
    name = 'admin'
    email = ''
    link = ''
  [params.search]
    enable = true
    type = 'lunr'

[menus]
  [[menu.main]]
    name = 'Giới thiệu'
    pageRef = '/posts/gioi-thieu/'
    weight = 1
  [[menu.main]]
    name = 'Cây xanh'
    pageRef = '/categories/cay-xanh/'
    weight = 2

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[caches]
  [caches.images]
      dir = ':cacheDir/images'
